// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: accounts/accounts.proto

package accountsconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pramanapi "github.com/taomics/pramanapi"
	accounts "github.com/taomics/pramanapi/accounts"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AccountsServiceName is the fully-qualified name of the AccountsService service.
	AccountsServiceName = "taomics.praman.accounts.AccountsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccountsServiceCurrentUserProcedure is the fully-qualified name of the AccountsService's
	// CurrentUser RPC.
	AccountsServiceCurrentUserProcedure = "/taomics.praman.accounts.AccountsService/CurrentUser"
	// AccountsServiceRegisterUserProcedure is the fully-qualified name of the AccountsService's
	// RegisterUser RPC.
	AccountsServiceRegisterUserProcedure = "/taomics.praman.accounts.AccountsService/RegisterUser"
	// AccountsServiceUpdateUserProcedure is the fully-qualified name of the AccountsService's
	// UpdateUser RPC.
	AccountsServiceUpdateUserProcedure = "/taomics.praman.accounts.AccountsService/UpdateUser"
	// AccountsServiceDisableAccountProcedure is the fully-qualified name of the AccountsService's
	// DisableAccount RPC.
	AccountsServiceDisableAccountProcedure = "/taomics.praman.accounts.AccountsService/DisableAccount"
	// AccountsServiceVerifyEmailProcedure is the fully-qualified name of the AccountsService's
	// VerifyEmail RPC.
	AccountsServiceVerifyEmailProcedure = "/taomics.praman.accounts.AccountsService/VerifyEmail"
	// AccountsServiceSendVerificationEmailProcedure is the fully-qualified name of the
	// AccountsService's SendVerificationEmail RPC.
	AccountsServiceSendVerificationEmailProcedure = "/taomics.praman.accounts.AccountsService/SendVerificationEmail"
	// AccountsServiceCurrentAdvisorProcedure is the fully-qualified name of the AccountsService's
	// CurrentAdvisor RPC.
	AccountsServiceCurrentAdvisorProcedure = "/taomics.praman.accounts.AccountsService/CurrentAdvisor"
	// AccountsServiceUpdateAdvisorProcedure is the fully-qualified name of the AccountsService's
	// UpdateAdvisor RPC.
	AccountsServiceUpdateAdvisorProcedure = "/taomics.praman.accounts.AccountsService/UpdateAdvisor"
	// AccountsServiceCreateAuthorizationProcedure is the fully-qualified name of the AccountsService's
	// CreateAuthorization RPC.
	AccountsServiceCreateAuthorizationProcedure = "/taomics.praman.accounts.AccountsService/CreateAuthorization"
	// AccountsServiceRetrieveAuthorizationProcedure is the fully-qualified name of the
	// AccountsService's RetrieveAuthorization RPC.
	AccountsServiceRetrieveAuthorizationProcedure = "/taomics.praman.accounts.AccountsService/RetrieveAuthorization"
	// AccountsServiceGrantAuthorizationProcedure is the fully-qualified name of the AccountsService's
	// GrantAuthorization RPC.
	AccountsServiceGrantAuthorizationProcedure = "/taomics.praman.accounts.AccountsService/GrantAuthorization"
)

// AccountsServiceClient is a client for the taomics.praman.accounts.AccountsService service.
type AccountsServiceClient interface {
	// Gets the current user profile using authorization header.
	//
	// Errors:
	//   - PERMISSION_DENIED (7): The requester does not have a user permission.
	CurrentUser(context.Context, *connect.Request[pramanapi.Empty]) (*connect.Response[accounts.AccountsUserFetchResponse], error)
	// Register as user.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	RegisterUser(context.Context, *connect.Request[accounts.AccountsUserCreationRequest]) (*connect.Response[accounts.AccountsUserCreationResponse], error)
	// Updates current user profile.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	//   - PERMISSION_DENIED (7): The requester does not have a user permission.
	UpdateUser(context.Context, *connect.Request[accounts.AccountsUserUpdateRequest]) (*connect.Response[accounts.AccountsUserUpdateResponse], error)
	// Disable current user account (account_email).
	//
	// Errors:
	//   - NOT_FOUND (5): The specified user id does not exist.
	//   - PERMISSION_DENIED (7): The requester does not have a user permission.
	DisableAccount(context.Context, *connect.Request[pramanapi.Empty]) (*connect.Response[pramanapi.Empty], error)
	// Verify current user email.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	//   - PERMISSION_DENIED (7): The requester does not have a user permission.
	//   - FAILED_PRECONDITION (9): The current user have some problems.
	VerifyEmail(context.Context, *connect.Request[accounts.VerifyEmailRequest]) (*connect.Response[pramanapi.Empty], error)
	// Send verification email to current user email.
	//
	// Errors:
	//   - PERMISSION_DENIED (7): The requester does not have a user permission
	//   - FAILED_PRECONDITION (9): The current user have some problems.
	SendVerificationEmail(context.Context, *connect.Request[pramanapi.Empty]) (*connect.Response[pramanapi.Empty], error)
	// Gets the current advisor profile using authorization header.
	//
	// Errors:
	//   - PERMISSION_DENIED (7): The requester does not have a advisor
	//     permission.
	CurrentAdvisor(context.Context, *connect.Request[pramanapi.Empty]) (*connect.Response[accounts.AccountsAdvisorFetchResponse], error)
	// Updates current advisor profile.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	//   - PERMISSION_DENIED (7): The requester does not have a user permission.
	UpdateAdvisor(context.Context, *connect.Request[accounts.AccountsAdvisorUpdateRequest]) (*connect.Response[accounts.AccountsAdvisorUpdateResponse], error)
	// Create an authorization request.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	//   - PERMISSION_DENIED (7): The requester does not have a advisor
	//     permission.
	CreateAuthorization(context.Context, *connect.Request[accounts.AccountsAuthorizationCreationRequest]) (*connect.Response[accounts.AccountsAuthorizationCreationResponse], error)
	// Gets an authorization request.
	//
	// Errors:
	//   - NOT_FOUND (5): The specified authorization id does not exist.
	//   - PERMISSION_DENIED (7): The requester does not have a user permission.
	RetrieveAuthorization(context.Context, *connect.Request[accounts.AccountsAuthorizationRetrievalRequest]) (*connect.Response[accounts.AccountsAuthorizationRetrievalResponse], error)
	// Grant an authorization request.
	//
	// Errors:
	//   - NOT_FOUND (5): The specified authorization id does not exist.
	//   - PERMISSION_DENIED (7):
	//   - The requester does not have a user permission.
	//   - The specified authorization id is for the requester.
	//   - FAILED_PRECONDITION (9): The specified authorization id was already
	//     granted.
	GrantAuthorization(context.Context, *connect.Request[accounts.AccountsAuthorizationGrantRequest]) (*connect.Response[accounts.AccountsAuthorizationGrantResponse], error)
}

// NewAccountsServiceClient constructs a client for the taomics.praman.accounts.AccountsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccountsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AccountsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	accountsServiceMethods := accounts.File_accounts_accounts_proto.Services().ByName("AccountsService").Methods()
	return &accountsServiceClient{
		currentUser: connect.NewClient[pramanapi.Empty, accounts.AccountsUserFetchResponse](
			httpClient,
			baseURL+AccountsServiceCurrentUserProcedure,
			connect.WithSchema(accountsServiceMethods.ByName("CurrentUser")),
			connect.WithClientOptions(opts...),
		),
		registerUser: connect.NewClient[accounts.AccountsUserCreationRequest, accounts.AccountsUserCreationResponse](
			httpClient,
			baseURL+AccountsServiceRegisterUserProcedure,
			connect.WithSchema(accountsServiceMethods.ByName("RegisterUser")),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[accounts.AccountsUserUpdateRequest, accounts.AccountsUserUpdateResponse](
			httpClient,
			baseURL+AccountsServiceUpdateUserProcedure,
			connect.WithSchema(accountsServiceMethods.ByName("UpdateUser")),
			connect.WithClientOptions(opts...),
		),
		disableAccount: connect.NewClient[pramanapi.Empty, pramanapi.Empty](
			httpClient,
			baseURL+AccountsServiceDisableAccountProcedure,
			connect.WithSchema(accountsServiceMethods.ByName("DisableAccount")),
			connect.WithClientOptions(opts...),
		),
		verifyEmail: connect.NewClient[accounts.VerifyEmailRequest, pramanapi.Empty](
			httpClient,
			baseURL+AccountsServiceVerifyEmailProcedure,
			connect.WithSchema(accountsServiceMethods.ByName("VerifyEmail")),
			connect.WithClientOptions(opts...),
		),
		sendVerificationEmail: connect.NewClient[pramanapi.Empty, pramanapi.Empty](
			httpClient,
			baseURL+AccountsServiceSendVerificationEmailProcedure,
			connect.WithSchema(accountsServiceMethods.ByName("SendVerificationEmail")),
			connect.WithClientOptions(opts...),
		),
		currentAdvisor: connect.NewClient[pramanapi.Empty, accounts.AccountsAdvisorFetchResponse](
			httpClient,
			baseURL+AccountsServiceCurrentAdvisorProcedure,
			connect.WithSchema(accountsServiceMethods.ByName("CurrentAdvisor")),
			connect.WithClientOptions(opts...),
		),
		updateAdvisor: connect.NewClient[accounts.AccountsAdvisorUpdateRequest, accounts.AccountsAdvisorUpdateResponse](
			httpClient,
			baseURL+AccountsServiceUpdateAdvisorProcedure,
			connect.WithSchema(accountsServiceMethods.ByName("UpdateAdvisor")),
			connect.WithClientOptions(opts...),
		),
		createAuthorization: connect.NewClient[accounts.AccountsAuthorizationCreationRequest, accounts.AccountsAuthorizationCreationResponse](
			httpClient,
			baseURL+AccountsServiceCreateAuthorizationProcedure,
			connect.WithSchema(accountsServiceMethods.ByName("CreateAuthorization")),
			connect.WithClientOptions(opts...),
		),
		retrieveAuthorization: connect.NewClient[accounts.AccountsAuthorizationRetrievalRequest, accounts.AccountsAuthorizationRetrievalResponse](
			httpClient,
			baseURL+AccountsServiceRetrieveAuthorizationProcedure,
			connect.WithSchema(accountsServiceMethods.ByName("RetrieveAuthorization")),
			connect.WithClientOptions(opts...),
		),
		grantAuthorization: connect.NewClient[accounts.AccountsAuthorizationGrantRequest, accounts.AccountsAuthorizationGrantResponse](
			httpClient,
			baseURL+AccountsServiceGrantAuthorizationProcedure,
			connect.WithSchema(accountsServiceMethods.ByName("GrantAuthorization")),
			connect.WithClientOptions(opts...),
		),
	}
}

// accountsServiceClient implements AccountsServiceClient.
type accountsServiceClient struct {
	currentUser           *connect.Client[pramanapi.Empty, accounts.AccountsUserFetchResponse]
	registerUser          *connect.Client[accounts.AccountsUserCreationRequest, accounts.AccountsUserCreationResponse]
	updateUser            *connect.Client[accounts.AccountsUserUpdateRequest, accounts.AccountsUserUpdateResponse]
	disableAccount        *connect.Client[pramanapi.Empty, pramanapi.Empty]
	verifyEmail           *connect.Client[accounts.VerifyEmailRequest, pramanapi.Empty]
	sendVerificationEmail *connect.Client[pramanapi.Empty, pramanapi.Empty]
	currentAdvisor        *connect.Client[pramanapi.Empty, accounts.AccountsAdvisorFetchResponse]
	updateAdvisor         *connect.Client[accounts.AccountsAdvisorUpdateRequest, accounts.AccountsAdvisorUpdateResponse]
	createAuthorization   *connect.Client[accounts.AccountsAuthorizationCreationRequest, accounts.AccountsAuthorizationCreationResponse]
	retrieveAuthorization *connect.Client[accounts.AccountsAuthorizationRetrievalRequest, accounts.AccountsAuthorizationRetrievalResponse]
	grantAuthorization    *connect.Client[accounts.AccountsAuthorizationGrantRequest, accounts.AccountsAuthorizationGrantResponse]
}

// CurrentUser calls taomics.praman.accounts.AccountsService.CurrentUser.
func (c *accountsServiceClient) CurrentUser(ctx context.Context, req *connect.Request[pramanapi.Empty]) (*connect.Response[accounts.AccountsUserFetchResponse], error) {
	return c.currentUser.CallUnary(ctx, req)
}

// RegisterUser calls taomics.praman.accounts.AccountsService.RegisterUser.
func (c *accountsServiceClient) RegisterUser(ctx context.Context, req *connect.Request[accounts.AccountsUserCreationRequest]) (*connect.Response[accounts.AccountsUserCreationResponse], error) {
	return c.registerUser.CallUnary(ctx, req)
}

// UpdateUser calls taomics.praman.accounts.AccountsService.UpdateUser.
func (c *accountsServiceClient) UpdateUser(ctx context.Context, req *connect.Request[accounts.AccountsUserUpdateRequest]) (*connect.Response[accounts.AccountsUserUpdateResponse], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// DisableAccount calls taomics.praman.accounts.AccountsService.DisableAccount.
func (c *accountsServiceClient) DisableAccount(ctx context.Context, req *connect.Request[pramanapi.Empty]) (*connect.Response[pramanapi.Empty], error) {
	return c.disableAccount.CallUnary(ctx, req)
}

// VerifyEmail calls taomics.praman.accounts.AccountsService.VerifyEmail.
func (c *accountsServiceClient) VerifyEmail(ctx context.Context, req *connect.Request[accounts.VerifyEmailRequest]) (*connect.Response[pramanapi.Empty], error) {
	return c.verifyEmail.CallUnary(ctx, req)
}

// SendVerificationEmail calls taomics.praman.accounts.AccountsService.SendVerificationEmail.
func (c *accountsServiceClient) SendVerificationEmail(ctx context.Context, req *connect.Request[pramanapi.Empty]) (*connect.Response[pramanapi.Empty], error) {
	return c.sendVerificationEmail.CallUnary(ctx, req)
}

// CurrentAdvisor calls taomics.praman.accounts.AccountsService.CurrentAdvisor.
func (c *accountsServiceClient) CurrentAdvisor(ctx context.Context, req *connect.Request[pramanapi.Empty]) (*connect.Response[accounts.AccountsAdvisorFetchResponse], error) {
	return c.currentAdvisor.CallUnary(ctx, req)
}

// UpdateAdvisor calls taomics.praman.accounts.AccountsService.UpdateAdvisor.
func (c *accountsServiceClient) UpdateAdvisor(ctx context.Context, req *connect.Request[accounts.AccountsAdvisorUpdateRequest]) (*connect.Response[accounts.AccountsAdvisorUpdateResponse], error) {
	return c.updateAdvisor.CallUnary(ctx, req)
}

// CreateAuthorization calls taomics.praman.accounts.AccountsService.CreateAuthorization.
func (c *accountsServiceClient) CreateAuthorization(ctx context.Context, req *connect.Request[accounts.AccountsAuthorizationCreationRequest]) (*connect.Response[accounts.AccountsAuthorizationCreationResponse], error) {
	return c.createAuthorization.CallUnary(ctx, req)
}

// RetrieveAuthorization calls taomics.praman.accounts.AccountsService.RetrieveAuthorization.
func (c *accountsServiceClient) RetrieveAuthorization(ctx context.Context, req *connect.Request[accounts.AccountsAuthorizationRetrievalRequest]) (*connect.Response[accounts.AccountsAuthorizationRetrievalResponse], error) {
	return c.retrieveAuthorization.CallUnary(ctx, req)
}

// GrantAuthorization calls taomics.praman.accounts.AccountsService.GrantAuthorization.
func (c *accountsServiceClient) GrantAuthorization(ctx context.Context, req *connect.Request[accounts.AccountsAuthorizationGrantRequest]) (*connect.Response[accounts.AccountsAuthorizationGrantResponse], error) {
	return c.grantAuthorization.CallUnary(ctx, req)
}

// AccountsServiceHandler is an implementation of the taomics.praman.accounts.AccountsService
// service.
type AccountsServiceHandler interface {
	// Gets the current user profile using authorization header.
	//
	// Errors:
	//   - PERMISSION_DENIED (7): The requester does not have a user permission.
	CurrentUser(context.Context, *connect.Request[pramanapi.Empty]) (*connect.Response[accounts.AccountsUserFetchResponse], error)
	// Register as user.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	RegisterUser(context.Context, *connect.Request[accounts.AccountsUserCreationRequest]) (*connect.Response[accounts.AccountsUserCreationResponse], error)
	// Updates current user profile.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	//   - PERMISSION_DENIED (7): The requester does not have a user permission.
	UpdateUser(context.Context, *connect.Request[accounts.AccountsUserUpdateRequest]) (*connect.Response[accounts.AccountsUserUpdateResponse], error)
	// Disable current user account (account_email).
	//
	// Errors:
	//   - NOT_FOUND (5): The specified user id does not exist.
	//   - PERMISSION_DENIED (7): The requester does not have a user permission.
	DisableAccount(context.Context, *connect.Request[pramanapi.Empty]) (*connect.Response[pramanapi.Empty], error)
	// Verify current user email.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	//   - PERMISSION_DENIED (7): The requester does not have a user permission.
	//   - FAILED_PRECONDITION (9): The current user have some problems.
	VerifyEmail(context.Context, *connect.Request[accounts.VerifyEmailRequest]) (*connect.Response[pramanapi.Empty], error)
	// Send verification email to current user email.
	//
	// Errors:
	//   - PERMISSION_DENIED (7): The requester does not have a user permission
	//   - FAILED_PRECONDITION (9): The current user have some problems.
	SendVerificationEmail(context.Context, *connect.Request[pramanapi.Empty]) (*connect.Response[pramanapi.Empty], error)
	// Gets the current advisor profile using authorization header.
	//
	// Errors:
	//   - PERMISSION_DENIED (7): The requester does not have a advisor
	//     permission.
	CurrentAdvisor(context.Context, *connect.Request[pramanapi.Empty]) (*connect.Response[accounts.AccountsAdvisorFetchResponse], error)
	// Updates current advisor profile.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	//   - PERMISSION_DENIED (7): The requester does not have a user permission.
	UpdateAdvisor(context.Context, *connect.Request[accounts.AccountsAdvisorUpdateRequest]) (*connect.Response[accounts.AccountsAdvisorUpdateResponse], error)
	// Create an authorization request.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	//   - PERMISSION_DENIED (7): The requester does not have a advisor
	//     permission.
	CreateAuthorization(context.Context, *connect.Request[accounts.AccountsAuthorizationCreationRequest]) (*connect.Response[accounts.AccountsAuthorizationCreationResponse], error)
	// Gets an authorization request.
	//
	// Errors:
	//   - NOT_FOUND (5): The specified authorization id does not exist.
	//   - PERMISSION_DENIED (7): The requester does not have a user permission.
	RetrieveAuthorization(context.Context, *connect.Request[accounts.AccountsAuthorizationRetrievalRequest]) (*connect.Response[accounts.AccountsAuthorizationRetrievalResponse], error)
	// Grant an authorization request.
	//
	// Errors:
	//   - NOT_FOUND (5): The specified authorization id does not exist.
	//   - PERMISSION_DENIED (7):
	//   - The requester does not have a user permission.
	//   - The specified authorization id is for the requester.
	//   - FAILED_PRECONDITION (9): The specified authorization id was already
	//     granted.
	GrantAuthorization(context.Context, *connect.Request[accounts.AccountsAuthorizationGrantRequest]) (*connect.Response[accounts.AccountsAuthorizationGrantResponse], error)
}

// NewAccountsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccountsServiceHandler(svc AccountsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	accountsServiceMethods := accounts.File_accounts_accounts_proto.Services().ByName("AccountsService").Methods()
	accountsServiceCurrentUserHandler := connect.NewUnaryHandler(
		AccountsServiceCurrentUserProcedure,
		svc.CurrentUser,
		connect.WithSchema(accountsServiceMethods.ByName("CurrentUser")),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceRegisterUserHandler := connect.NewUnaryHandler(
		AccountsServiceRegisterUserProcedure,
		svc.RegisterUser,
		connect.WithSchema(accountsServiceMethods.ByName("RegisterUser")),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceUpdateUserHandler := connect.NewUnaryHandler(
		AccountsServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(accountsServiceMethods.ByName("UpdateUser")),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceDisableAccountHandler := connect.NewUnaryHandler(
		AccountsServiceDisableAccountProcedure,
		svc.DisableAccount,
		connect.WithSchema(accountsServiceMethods.ByName("DisableAccount")),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceVerifyEmailHandler := connect.NewUnaryHandler(
		AccountsServiceVerifyEmailProcedure,
		svc.VerifyEmail,
		connect.WithSchema(accountsServiceMethods.ByName("VerifyEmail")),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceSendVerificationEmailHandler := connect.NewUnaryHandler(
		AccountsServiceSendVerificationEmailProcedure,
		svc.SendVerificationEmail,
		connect.WithSchema(accountsServiceMethods.ByName("SendVerificationEmail")),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceCurrentAdvisorHandler := connect.NewUnaryHandler(
		AccountsServiceCurrentAdvisorProcedure,
		svc.CurrentAdvisor,
		connect.WithSchema(accountsServiceMethods.ByName("CurrentAdvisor")),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceUpdateAdvisorHandler := connect.NewUnaryHandler(
		AccountsServiceUpdateAdvisorProcedure,
		svc.UpdateAdvisor,
		connect.WithSchema(accountsServiceMethods.ByName("UpdateAdvisor")),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceCreateAuthorizationHandler := connect.NewUnaryHandler(
		AccountsServiceCreateAuthorizationProcedure,
		svc.CreateAuthorization,
		connect.WithSchema(accountsServiceMethods.ByName("CreateAuthorization")),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceRetrieveAuthorizationHandler := connect.NewUnaryHandler(
		AccountsServiceRetrieveAuthorizationProcedure,
		svc.RetrieveAuthorization,
		connect.WithSchema(accountsServiceMethods.ByName("RetrieveAuthorization")),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceGrantAuthorizationHandler := connect.NewUnaryHandler(
		AccountsServiceGrantAuthorizationProcedure,
		svc.GrantAuthorization,
		connect.WithSchema(accountsServiceMethods.ByName("GrantAuthorization")),
		connect.WithHandlerOptions(opts...),
	)
	return "/taomics.praman.accounts.AccountsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccountsServiceCurrentUserProcedure:
			accountsServiceCurrentUserHandler.ServeHTTP(w, r)
		case AccountsServiceRegisterUserProcedure:
			accountsServiceRegisterUserHandler.ServeHTTP(w, r)
		case AccountsServiceUpdateUserProcedure:
			accountsServiceUpdateUserHandler.ServeHTTP(w, r)
		case AccountsServiceDisableAccountProcedure:
			accountsServiceDisableAccountHandler.ServeHTTP(w, r)
		case AccountsServiceVerifyEmailProcedure:
			accountsServiceVerifyEmailHandler.ServeHTTP(w, r)
		case AccountsServiceSendVerificationEmailProcedure:
			accountsServiceSendVerificationEmailHandler.ServeHTTP(w, r)
		case AccountsServiceCurrentAdvisorProcedure:
			accountsServiceCurrentAdvisorHandler.ServeHTTP(w, r)
		case AccountsServiceUpdateAdvisorProcedure:
			accountsServiceUpdateAdvisorHandler.ServeHTTP(w, r)
		case AccountsServiceCreateAuthorizationProcedure:
			accountsServiceCreateAuthorizationHandler.ServeHTTP(w, r)
		case AccountsServiceRetrieveAuthorizationProcedure:
			accountsServiceRetrieveAuthorizationHandler.ServeHTTP(w, r)
		case AccountsServiceGrantAuthorizationProcedure:
			accountsServiceGrantAuthorizationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccountsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAccountsServiceHandler struct{}

func (UnimplementedAccountsServiceHandler) CurrentUser(context.Context, *connect.Request[pramanapi.Empty]) (*connect.Response[accounts.AccountsUserFetchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.accounts.AccountsService.CurrentUser is not implemented"))
}

func (UnimplementedAccountsServiceHandler) RegisterUser(context.Context, *connect.Request[accounts.AccountsUserCreationRequest]) (*connect.Response[accounts.AccountsUserCreationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.accounts.AccountsService.RegisterUser is not implemented"))
}

func (UnimplementedAccountsServiceHandler) UpdateUser(context.Context, *connect.Request[accounts.AccountsUserUpdateRequest]) (*connect.Response[accounts.AccountsUserUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.accounts.AccountsService.UpdateUser is not implemented"))
}

func (UnimplementedAccountsServiceHandler) DisableAccount(context.Context, *connect.Request[pramanapi.Empty]) (*connect.Response[pramanapi.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.accounts.AccountsService.DisableAccount is not implemented"))
}

func (UnimplementedAccountsServiceHandler) VerifyEmail(context.Context, *connect.Request[accounts.VerifyEmailRequest]) (*connect.Response[pramanapi.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.accounts.AccountsService.VerifyEmail is not implemented"))
}

func (UnimplementedAccountsServiceHandler) SendVerificationEmail(context.Context, *connect.Request[pramanapi.Empty]) (*connect.Response[pramanapi.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.accounts.AccountsService.SendVerificationEmail is not implemented"))
}

func (UnimplementedAccountsServiceHandler) CurrentAdvisor(context.Context, *connect.Request[pramanapi.Empty]) (*connect.Response[accounts.AccountsAdvisorFetchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.accounts.AccountsService.CurrentAdvisor is not implemented"))
}

func (UnimplementedAccountsServiceHandler) UpdateAdvisor(context.Context, *connect.Request[accounts.AccountsAdvisorUpdateRequest]) (*connect.Response[accounts.AccountsAdvisorUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.accounts.AccountsService.UpdateAdvisor is not implemented"))
}

func (UnimplementedAccountsServiceHandler) CreateAuthorization(context.Context, *connect.Request[accounts.AccountsAuthorizationCreationRequest]) (*connect.Response[accounts.AccountsAuthorizationCreationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.accounts.AccountsService.CreateAuthorization is not implemented"))
}

func (UnimplementedAccountsServiceHandler) RetrieveAuthorization(context.Context, *connect.Request[accounts.AccountsAuthorizationRetrievalRequest]) (*connect.Response[accounts.AccountsAuthorizationRetrievalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.accounts.AccountsService.RetrieveAuthorization is not implemented"))
}

func (UnimplementedAccountsServiceHandler) GrantAuthorization(context.Context, *connect.Request[accounts.AccountsAuthorizationGrantRequest]) (*connect.Response[accounts.AccountsAuthorizationGrantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.accounts.AccountsService.GrantAuthorization is not implemented"))
}
