// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: healthfeedback/healthfeedback.proto

package healthfeedbackconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pramanapi "github.com/taomics/pramanapi"
	healthfeedback "github.com/taomics/pramanapi/healthfeedback"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HealthFeedbackServiceName is the fully-qualified name of the HealthFeedbackService service.
	HealthFeedbackServiceName = "taomics.praman.healthfeedback.HealthFeedbackService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HealthFeedbackServiceGetHealthFeedbackProcedure is the fully-qualified name of the
	// HealthFeedbackService's GetHealthFeedback RPC.
	HealthFeedbackServiceGetHealthFeedbackProcedure = "/taomics.praman.healthfeedback.HealthFeedbackService/GetHealthFeedback"
	// HealthFeedbackServiceRateHealthFeedbackProcedure is the fully-qualified name of the
	// HealthFeedbackService's RateHealthFeedback RPC.
	HealthFeedbackServiceRateHealthFeedbackProcedure = "/taomics.praman.healthfeedback.HealthFeedbackService/RateHealthFeedback"
	// HealthFeedbackServiceSetHealthModeProcedure is the fully-qualified name of the
	// HealthFeedbackService's SetHealthMode RPC.
	HealthFeedbackServiceSetHealthModeProcedure = "/taomics.praman.healthfeedback.HealthFeedbackService/SetHealthMode"
)

// HealthFeedbackServiceClient is a client for the
// taomics.praman.healthfeedback.HealthFeedbackService service.
type HealthFeedbackServiceClient interface {
	// GetHealthFeedback
	//
	// Errors:
	//   - NOT_FOUND (5): there is no feedback.
	//   - FAILED_PRECONDITION (9): health mode is not set.
	GetHealthFeedback(context.Context, *connect.Request[healthfeedback.GetHealthFeedbackRequest]) (*connect.Response[healthfeedback.GetHealthFeedbackResponse], error)
	// RateHealthFeedback
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): id is invalid, or rating is UNRATED.
	RateHealthFeedback(context.Context, *connect.Request[healthfeedback.RateHealthFeedbackRequest]) (*connect.Response[pramanapi.Empty], error)
	// SetHealthMode
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): mode is missing.
	SetHealthMode(context.Context, *connect.Request[healthfeedback.SetHealthModeRequest]) (*connect.Response[pramanapi.Empty], error)
}

// NewHealthFeedbackServiceClient constructs a client for the
// taomics.praman.healthfeedback.HealthFeedbackService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHealthFeedbackServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HealthFeedbackServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	healthFeedbackServiceMethods := healthfeedback.File_healthfeedback_healthfeedback_proto.Services().ByName("HealthFeedbackService").Methods()
	return &healthFeedbackServiceClient{
		getHealthFeedback: connect.NewClient[healthfeedback.GetHealthFeedbackRequest, healthfeedback.GetHealthFeedbackResponse](
			httpClient,
			baseURL+HealthFeedbackServiceGetHealthFeedbackProcedure,
			connect.WithSchema(healthFeedbackServiceMethods.ByName("GetHealthFeedback")),
			connect.WithClientOptions(opts...),
		),
		rateHealthFeedback: connect.NewClient[healthfeedback.RateHealthFeedbackRequest, pramanapi.Empty](
			httpClient,
			baseURL+HealthFeedbackServiceRateHealthFeedbackProcedure,
			connect.WithSchema(healthFeedbackServiceMethods.ByName("RateHealthFeedback")),
			connect.WithClientOptions(opts...),
		),
		setHealthMode: connect.NewClient[healthfeedback.SetHealthModeRequest, pramanapi.Empty](
			httpClient,
			baseURL+HealthFeedbackServiceSetHealthModeProcedure,
			connect.WithSchema(healthFeedbackServiceMethods.ByName("SetHealthMode")),
			connect.WithClientOptions(opts...),
		),
	}
}

// healthFeedbackServiceClient implements HealthFeedbackServiceClient.
type healthFeedbackServiceClient struct {
	getHealthFeedback  *connect.Client[healthfeedback.GetHealthFeedbackRequest, healthfeedback.GetHealthFeedbackResponse]
	rateHealthFeedback *connect.Client[healthfeedback.RateHealthFeedbackRequest, pramanapi.Empty]
	setHealthMode      *connect.Client[healthfeedback.SetHealthModeRequest, pramanapi.Empty]
}

// GetHealthFeedback calls taomics.praman.healthfeedback.HealthFeedbackService.GetHealthFeedback.
func (c *healthFeedbackServiceClient) GetHealthFeedback(ctx context.Context, req *connect.Request[healthfeedback.GetHealthFeedbackRequest]) (*connect.Response[healthfeedback.GetHealthFeedbackResponse], error) {
	return c.getHealthFeedback.CallUnary(ctx, req)
}

// RateHealthFeedback calls taomics.praman.healthfeedback.HealthFeedbackService.RateHealthFeedback.
func (c *healthFeedbackServiceClient) RateHealthFeedback(ctx context.Context, req *connect.Request[healthfeedback.RateHealthFeedbackRequest]) (*connect.Response[pramanapi.Empty], error) {
	return c.rateHealthFeedback.CallUnary(ctx, req)
}

// SetHealthMode calls taomics.praman.healthfeedback.HealthFeedbackService.SetHealthMode.
func (c *healthFeedbackServiceClient) SetHealthMode(ctx context.Context, req *connect.Request[healthfeedback.SetHealthModeRequest]) (*connect.Response[pramanapi.Empty], error) {
	return c.setHealthMode.CallUnary(ctx, req)
}

// HealthFeedbackServiceHandler is an implementation of the
// taomics.praman.healthfeedback.HealthFeedbackService service.
type HealthFeedbackServiceHandler interface {
	// GetHealthFeedback
	//
	// Errors:
	//   - NOT_FOUND (5): there is no feedback.
	//   - FAILED_PRECONDITION (9): health mode is not set.
	GetHealthFeedback(context.Context, *connect.Request[healthfeedback.GetHealthFeedbackRequest]) (*connect.Response[healthfeedback.GetHealthFeedbackResponse], error)
	// RateHealthFeedback
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): id is invalid, or rating is UNRATED.
	RateHealthFeedback(context.Context, *connect.Request[healthfeedback.RateHealthFeedbackRequest]) (*connect.Response[pramanapi.Empty], error)
	// SetHealthMode
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): mode is missing.
	SetHealthMode(context.Context, *connect.Request[healthfeedback.SetHealthModeRequest]) (*connect.Response[pramanapi.Empty], error)
}

// NewHealthFeedbackServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHealthFeedbackServiceHandler(svc HealthFeedbackServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	healthFeedbackServiceMethods := healthfeedback.File_healthfeedback_healthfeedback_proto.Services().ByName("HealthFeedbackService").Methods()
	healthFeedbackServiceGetHealthFeedbackHandler := connect.NewUnaryHandler(
		HealthFeedbackServiceGetHealthFeedbackProcedure,
		svc.GetHealthFeedback,
		connect.WithSchema(healthFeedbackServiceMethods.ByName("GetHealthFeedback")),
		connect.WithHandlerOptions(opts...),
	)
	healthFeedbackServiceRateHealthFeedbackHandler := connect.NewUnaryHandler(
		HealthFeedbackServiceRateHealthFeedbackProcedure,
		svc.RateHealthFeedback,
		connect.WithSchema(healthFeedbackServiceMethods.ByName("RateHealthFeedback")),
		connect.WithHandlerOptions(opts...),
	)
	healthFeedbackServiceSetHealthModeHandler := connect.NewUnaryHandler(
		HealthFeedbackServiceSetHealthModeProcedure,
		svc.SetHealthMode,
		connect.WithSchema(healthFeedbackServiceMethods.ByName("SetHealthMode")),
		connect.WithHandlerOptions(opts...),
	)
	return "/taomics.praman.healthfeedback.HealthFeedbackService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HealthFeedbackServiceGetHealthFeedbackProcedure:
			healthFeedbackServiceGetHealthFeedbackHandler.ServeHTTP(w, r)
		case HealthFeedbackServiceRateHealthFeedbackProcedure:
			healthFeedbackServiceRateHealthFeedbackHandler.ServeHTTP(w, r)
		case HealthFeedbackServiceSetHealthModeProcedure:
			healthFeedbackServiceSetHealthModeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHealthFeedbackServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHealthFeedbackServiceHandler struct{}

func (UnimplementedHealthFeedbackServiceHandler) GetHealthFeedback(context.Context, *connect.Request[healthfeedback.GetHealthFeedbackRequest]) (*connect.Response[healthfeedback.GetHealthFeedbackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.healthfeedback.HealthFeedbackService.GetHealthFeedback is not implemented"))
}

func (UnimplementedHealthFeedbackServiceHandler) RateHealthFeedback(context.Context, *connect.Request[healthfeedback.RateHealthFeedbackRequest]) (*connect.Response[pramanapi.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.healthfeedback.HealthFeedbackService.RateHealthFeedback is not implemented"))
}

func (UnimplementedHealthFeedbackServiceHandler) SetHealthMode(context.Context, *connect.Request[healthfeedback.SetHealthModeRequest]) (*connect.Response[pramanapi.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.healthfeedback.HealthFeedbackService.SetHealthMode is not implemented"))
}
