// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: healthcheck/healthcheck.proto

package healthcheckconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	healthcheck "github.com/taomics/pramanapi/healthcheck"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HealthCheckServiceName is the fully-qualified name of the HealthCheckService service.
	HealthCheckServiceName = "taomics.praman.healthcheck.HealthCheckService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HealthCheckServicePredictHealthCheckProcedure is the fully-qualified name of the
	// HealthCheckService's PredictHealthCheck RPC.
	HealthCheckServicePredictHealthCheckProcedure = "/taomics.praman.healthcheck.HealthCheckService/PredictHealthCheck"
	// HealthCheckServiceUploadHealthCheckResultProcedure is the fully-qualified name of the
	// HealthCheckService's UploadHealthCheckResult RPC.
	HealthCheckServiceUploadHealthCheckResultProcedure = "/taomics.praman.healthcheck.HealthCheckService/UploadHealthCheckResult"
)

// HealthCheckServiceClient is a client for the taomics.praman.healthcheck.HealthCheckService
// service.
type HealthCheckServiceClient interface {
	// Predict health check result in the future.
	//
	// Errors:
	//   - NOT_FOUND (5): The health check data is not found.
	PredictHealthCheck(context.Context, *connect.Request[healthcheck.HealthCheckPredictionRequest]) (*connect.Response[healthcheck.HealthCheckPredictionResponse], error)
	// Upload health check result.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): The upload data is invalid.
	//   - FAILED_PRECONDITION (9): The upload data is not acceptable.
	//   - ALREADY_EXISTS (6): The health check data is already exists.
	UploadHealthCheckResult(context.Context, *connect.Request[healthcheck.UploadHealthCheckResultRequest]) (*connect.Response[healthcheck.UploadHealthCheckResultResponse], error)
}

// NewHealthCheckServiceClient constructs a client for the
// taomics.praman.healthcheck.HealthCheckService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHealthCheckServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HealthCheckServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	healthCheckServiceMethods := healthcheck.File_healthcheck_healthcheck_proto.Services().ByName("HealthCheckService").Methods()
	return &healthCheckServiceClient{
		predictHealthCheck: connect.NewClient[healthcheck.HealthCheckPredictionRequest, healthcheck.HealthCheckPredictionResponse](
			httpClient,
			baseURL+HealthCheckServicePredictHealthCheckProcedure,
			connect.WithSchema(healthCheckServiceMethods.ByName("PredictHealthCheck")),
			connect.WithClientOptions(opts...),
		),
		uploadHealthCheckResult: connect.NewClient[healthcheck.UploadHealthCheckResultRequest, healthcheck.UploadHealthCheckResultResponse](
			httpClient,
			baseURL+HealthCheckServiceUploadHealthCheckResultProcedure,
			connect.WithSchema(healthCheckServiceMethods.ByName("UploadHealthCheckResult")),
			connect.WithClientOptions(opts...),
		),
	}
}

// healthCheckServiceClient implements HealthCheckServiceClient.
type healthCheckServiceClient struct {
	predictHealthCheck      *connect.Client[healthcheck.HealthCheckPredictionRequest, healthcheck.HealthCheckPredictionResponse]
	uploadHealthCheckResult *connect.Client[healthcheck.UploadHealthCheckResultRequest, healthcheck.UploadHealthCheckResultResponse]
}

// PredictHealthCheck calls taomics.praman.healthcheck.HealthCheckService.PredictHealthCheck.
func (c *healthCheckServiceClient) PredictHealthCheck(ctx context.Context, req *connect.Request[healthcheck.HealthCheckPredictionRequest]) (*connect.Response[healthcheck.HealthCheckPredictionResponse], error) {
	return c.predictHealthCheck.CallUnary(ctx, req)
}

// UploadHealthCheckResult calls
// taomics.praman.healthcheck.HealthCheckService.UploadHealthCheckResult.
func (c *healthCheckServiceClient) UploadHealthCheckResult(ctx context.Context, req *connect.Request[healthcheck.UploadHealthCheckResultRequest]) (*connect.Response[healthcheck.UploadHealthCheckResultResponse], error) {
	return c.uploadHealthCheckResult.CallUnary(ctx, req)
}

// HealthCheckServiceHandler is an implementation of the
// taomics.praman.healthcheck.HealthCheckService service.
type HealthCheckServiceHandler interface {
	// Predict health check result in the future.
	//
	// Errors:
	//   - NOT_FOUND (5): The health check data is not found.
	PredictHealthCheck(context.Context, *connect.Request[healthcheck.HealthCheckPredictionRequest]) (*connect.Response[healthcheck.HealthCheckPredictionResponse], error)
	// Upload health check result.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): The upload data is invalid.
	//   - FAILED_PRECONDITION (9): The upload data is not acceptable.
	//   - ALREADY_EXISTS (6): The health check data is already exists.
	UploadHealthCheckResult(context.Context, *connect.Request[healthcheck.UploadHealthCheckResultRequest]) (*connect.Response[healthcheck.UploadHealthCheckResultResponse], error)
}

// NewHealthCheckServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHealthCheckServiceHandler(svc HealthCheckServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	healthCheckServiceMethods := healthcheck.File_healthcheck_healthcheck_proto.Services().ByName("HealthCheckService").Methods()
	healthCheckServicePredictHealthCheckHandler := connect.NewUnaryHandler(
		HealthCheckServicePredictHealthCheckProcedure,
		svc.PredictHealthCheck,
		connect.WithSchema(healthCheckServiceMethods.ByName("PredictHealthCheck")),
		connect.WithHandlerOptions(opts...),
	)
	healthCheckServiceUploadHealthCheckResultHandler := connect.NewUnaryHandler(
		HealthCheckServiceUploadHealthCheckResultProcedure,
		svc.UploadHealthCheckResult,
		connect.WithSchema(healthCheckServiceMethods.ByName("UploadHealthCheckResult")),
		connect.WithHandlerOptions(opts...),
	)
	return "/taomics.praman.healthcheck.HealthCheckService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HealthCheckServicePredictHealthCheckProcedure:
			healthCheckServicePredictHealthCheckHandler.ServeHTTP(w, r)
		case HealthCheckServiceUploadHealthCheckResultProcedure:
			healthCheckServiceUploadHealthCheckResultHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHealthCheckServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHealthCheckServiceHandler struct{}

func (UnimplementedHealthCheckServiceHandler) PredictHealthCheck(context.Context, *connect.Request[healthcheck.HealthCheckPredictionRequest]) (*connect.Response[healthcheck.HealthCheckPredictionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.healthcheck.HealthCheckService.PredictHealthCheck is not implemented"))
}

func (UnimplementedHealthCheckServiceHandler) UploadHealthCheckResult(context.Context, *connect.Request[healthcheck.UploadHealthCheckResultRequest]) (*connect.Response[healthcheck.UploadHealthCheckResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.healthcheck.HealthCheckService.UploadHealthCheckResult is not implemented"))
}
