// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: researchstudy/researchstudy.proto

package researchstudyconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	researchstudy "github.com/taomics/pramanapi/researchstudy"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ResearchStudyServiceName is the fully-qualified name of the ResearchStudyService service.
	ResearchStudyServiceName = "taomics.praman.researchstudy.ResearchStudyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ResearchStudyServiceListResearchStudiesProcedure is the fully-qualified name of the
	// ResearchStudyService's ListResearchStudies RPC.
	ResearchStudyServiceListResearchStudiesProcedure = "/taomics.praman.researchstudy.ResearchStudyService/ListResearchStudies"
	// ResearchStudyServiceGetResearchStudyProcedure is the fully-qualified name of the
	// ResearchStudyService's GetResearchStudy RPC.
	ResearchStudyServiceGetResearchStudyProcedure = "/taomics.praman.researchstudy.ResearchStudyService/GetResearchStudy"
)

// ResearchStudyServiceClient is a client for the taomics.praman.researchstudy.ResearchStudyService
// service.
type ResearchStudyServiceClient interface {
	// List research studies visible to the current user.
	//
	// The response contains:
	//   - all public studies; and
	//   - non-public studies for which the current user is registered as a
	//     target.
	ListResearchStudies(context.Context, *connect.Request[researchstudy.ListResearchStudiesRequest]) (*connect.Response[researchstudy.ListResearchStudiesResponse], error)
	// Get detailed information about a research study.
	//
	// Detailed information is available only when the current user is registered
	// as a target of the specified study, including when the study is public.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): research_study_id is empty or invalid.
	//   - NOT_FOUND (5): The study does not exist or is not accessible to the
	//     current user.
	GetResearchStudy(context.Context, *connect.Request[researchstudy.GetResearchStudyRequest]) (*connect.Response[researchstudy.GetResearchStudyResponse], error)
}

// NewResearchStudyServiceClient constructs a client for the
// taomics.praman.researchstudy.ResearchStudyService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewResearchStudyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ResearchStudyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	researchStudyServiceMethods := researchstudy.File_researchstudy_researchstudy_proto.Services().ByName("ResearchStudyService").Methods()
	return &researchStudyServiceClient{
		listResearchStudies: connect.NewClient[researchstudy.ListResearchStudiesRequest, researchstudy.ListResearchStudiesResponse](
			httpClient,
			baseURL+ResearchStudyServiceListResearchStudiesProcedure,
			connect.WithSchema(researchStudyServiceMethods.ByName("ListResearchStudies")),
			connect.WithClientOptions(opts...),
		),
		getResearchStudy: connect.NewClient[researchstudy.GetResearchStudyRequest, researchstudy.GetResearchStudyResponse](
			httpClient,
			baseURL+ResearchStudyServiceGetResearchStudyProcedure,
			connect.WithSchema(researchStudyServiceMethods.ByName("GetResearchStudy")),
			connect.WithClientOptions(opts...),
		),
	}
}

// researchStudyServiceClient implements ResearchStudyServiceClient.
type researchStudyServiceClient struct {
	listResearchStudies *connect.Client[researchstudy.ListResearchStudiesRequest, researchstudy.ListResearchStudiesResponse]
	getResearchStudy    *connect.Client[researchstudy.GetResearchStudyRequest, researchstudy.GetResearchStudyResponse]
}

// ListResearchStudies calls taomics.praman.researchstudy.ResearchStudyService.ListResearchStudies.
func (c *researchStudyServiceClient) ListResearchStudies(ctx context.Context, req *connect.Request[researchstudy.ListResearchStudiesRequest]) (*connect.Response[researchstudy.ListResearchStudiesResponse], error) {
	return c.listResearchStudies.CallUnary(ctx, req)
}

// GetResearchStudy calls taomics.praman.researchstudy.ResearchStudyService.GetResearchStudy.
func (c *researchStudyServiceClient) GetResearchStudy(ctx context.Context, req *connect.Request[researchstudy.GetResearchStudyRequest]) (*connect.Response[researchstudy.GetResearchStudyResponse], error) {
	return c.getResearchStudy.CallUnary(ctx, req)
}

// ResearchStudyServiceHandler is an implementation of the
// taomics.praman.researchstudy.ResearchStudyService service.
type ResearchStudyServiceHandler interface {
	// List research studies visible to the current user.
	//
	// The response contains:
	//   - all public studies; and
	//   - non-public studies for which the current user is registered as a
	//     target.
	ListResearchStudies(context.Context, *connect.Request[researchstudy.ListResearchStudiesRequest]) (*connect.Response[researchstudy.ListResearchStudiesResponse], error)
	// Get detailed information about a research study.
	//
	// Detailed information is available only when the current user is registered
	// as a target of the specified study, including when the study is public.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): research_study_id is empty or invalid.
	//   - NOT_FOUND (5): The study does not exist or is not accessible to the
	//     current user.
	GetResearchStudy(context.Context, *connect.Request[researchstudy.GetResearchStudyRequest]) (*connect.Response[researchstudy.GetResearchStudyResponse], error)
}

// NewResearchStudyServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewResearchStudyServiceHandler(svc ResearchStudyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	researchStudyServiceMethods := researchstudy.File_researchstudy_researchstudy_proto.Services().ByName("ResearchStudyService").Methods()
	researchStudyServiceListResearchStudiesHandler := connect.NewUnaryHandler(
		ResearchStudyServiceListResearchStudiesProcedure,
		svc.ListResearchStudies,
		connect.WithSchema(researchStudyServiceMethods.ByName("ListResearchStudies")),
		connect.WithHandlerOptions(opts...),
	)
	researchStudyServiceGetResearchStudyHandler := connect.NewUnaryHandler(
		ResearchStudyServiceGetResearchStudyProcedure,
		svc.GetResearchStudy,
		connect.WithSchema(researchStudyServiceMethods.ByName("GetResearchStudy")),
		connect.WithHandlerOptions(opts...),
	)
	return "/taomics.praman.researchstudy.ResearchStudyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ResearchStudyServiceListResearchStudiesProcedure:
			researchStudyServiceListResearchStudiesHandler.ServeHTTP(w, r)
		case ResearchStudyServiceGetResearchStudyProcedure:
			researchStudyServiceGetResearchStudyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedResearchStudyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedResearchStudyServiceHandler struct{}

func (UnimplementedResearchStudyServiceHandler) ListResearchStudies(context.Context, *connect.Request[researchstudy.ListResearchStudiesRequest]) (*connect.Response[researchstudy.ListResearchStudiesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.researchstudy.ResearchStudyService.ListResearchStudies is not implemented"))
}

func (UnimplementedResearchStudyServiceHandler) GetResearchStudy(context.Context, *connect.Request[researchstudy.GetResearchStudyRequest]) (*connect.Response[researchstudy.GetResearchStudyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.researchstudy.ResearchStudyService.GetResearchStudy is not implemented"))
}
