// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: recordlog/recordlog.proto

package recordlogconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	recordlog "github.com/taomics/pramanapi/recordlog"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RecordLogServiceName is the fully-qualified name of the RecordLogService service.
	RecordLogServiceName = "taomics.praman.recordlog.RecordLogService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RecordLogServiceGetBodyMetricsLogProcedure is the fully-qualified name of the RecordLogService's
	// GetBodyMetricsLog RPC.
	RecordLogServiceGetBodyMetricsLogProcedure = "/taomics.praman.recordlog.RecordLogService/GetBodyMetricsLog"
	// RecordLogServiceGetSleepLogProcedure is the fully-qualified name of the RecordLogService's
	// GetSleepLog RPC.
	RecordLogServiceGetSleepLogProcedure = "/taomics.praman.recordlog.RecordLogService/GetSleepLog"
	// RecordLogServiceGetMealLogProcedure is the fully-qualified name of the RecordLogService's
	// GetMealLog RPC.
	RecordLogServiceGetMealLogProcedure = "/taomics.praman.recordlog.RecordLogService/GetMealLog"
	// RecordLogServiceGetAlcoholCaffeineLogProcedure is the fully-qualified name of the
	// RecordLogService's GetAlcoholCaffeineLog RPC.
	RecordLogServiceGetAlcoholCaffeineLogProcedure = "/taomics.praman.recordlog.RecordLogService/GetAlcoholCaffeineLog"
	// RecordLogServiceGetTabaccoLogProcedure is the fully-qualified name of the RecordLogService's
	// GetTabaccoLog RPC.
	RecordLogServiceGetTabaccoLogProcedure = "/taomics.praman.recordlog.RecordLogService/GetTabaccoLog"
	// RecordLogServiceGetActivityLogProcedure is the fully-qualified name of the RecordLogService's
	// GetActivityLog RPC.
	RecordLogServiceGetActivityLogProcedure = "/taomics.praman.recordlog.RecordLogService/GetActivityLog"
	// RecordLogServiceGetStressLogProcedure is the fully-qualified name of the RecordLogService's
	// GetStressLog RPC.
	RecordLogServiceGetStressLogProcedure = "/taomics.praman.recordlog.RecordLogService/GetStressLog"
	// RecordLogServiceGetStoolLogProcedure is the fully-qualified name of the RecordLogService's
	// GetStoolLog RPC.
	RecordLogServiceGetStoolLogProcedure = "/taomics.praman.recordlog.RecordLogService/GetStoolLog"
)

// RecordLogServiceClient is a client for the taomics.praman.recordlog.RecordLogService service.
type RecordLogServiceClient interface {
	// Gets the current user's log of body metrics.
	GetBodyMetricsLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.BodyMetricsLog], error)
	// Gets the current user's log of sleep journal.
	GetSleepLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.SleepLog], error)
	// Gets the current user's log of meal journal.
	GetMealLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.MealLog], error)
	// Gets the current user's log of alcohol and caffeine journal.
	GetAlcoholCaffeineLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.AlcoholCaffeineLog], error)
	// Gets the current user's log of tabacco journal.
	GetTabaccoLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.TabaccoLog], error)
	// Gets the current user's log of activity journal.
	GetActivityLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.ActivityLog], error)
	// Gets the current user's log of stress journal.
	GetStressLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.StressLog], error)
	// Gets the current user's log of stool journal.
	GetStoolLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.StoolLog], error)
}

// NewRecordLogServiceClient constructs a client for the taomics.praman.recordlog.RecordLogService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRecordLogServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RecordLogServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	recordLogServiceMethods := recordlog.File_recordlog_recordlog_proto.Services().ByName("RecordLogService").Methods()
	return &recordLogServiceClient{
		getBodyMetricsLog: connect.NewClient[recordlog.LogRequest, recordlog.BodyMetricsLog](
			httpClient,
			baseURL+RecordLogServiceGetBodyMetricsLogProcedure,
			connect.WithSchema(recordLogServiceMethods.ByName("GetBodyMetricsLog")),
			connect.WithClientOptions(opts...),
		),
		getSleepLog: connect.NewClient[recordlog.LogRequest, recordlog.SleepLog](
			httpClient,
			baseURL+RecordLogServiceGetSleepLogProcedure,
			connect.WithSchema(recordLogServiceMethods.ByName("GetSleepLog")),
			connect.WithClientOptions(opts...),
		),
		getMealLog: connect.NewClient[recordlog.LogRequest, recordlog.MealLog](
			httpClient,
			baseURL+RecordLogServiceGetMealLogProcedure,
			connect.WithSchema(recordLogServiceMethods.ByName("GetMealLog")),
			connect.WithClientOptions(opts...),
		),
		getAlcoholCaffeineLog: connect.NewClient[recordlog.LogRequest, recordlog.AlcoholCaffeineLog](
			httpClient,
			baseURL+RecordLogServiceGetAlcoholCaffeineLogProcedure,
			connect.WithSchema(recordLogServiceMethods.ByName("GetAlcoholCaffeineLog")),
			connect.WithClientOptions(opts...),
		),
		getTabaccoLog: connect.NewClient[recordlog.LogRequest, recordlog.TabaccoLog](
			httpClient,
			baseURL+RecordLogServiceGetTabaccoLogProcedure,
			connect.WithSchema(recordLogServiceMethods.ByName("GetTabaccoLog")),
			connect.WithClientOptions(opts...),
		),
		getActivityLog: connect.NewClient[recordlog.LogRequest, recordlog.ActivityLog](
			httpClient,
			baseURL+RecordLogServiceGetActivityLogProcedure,
			connect.WithSchema(recordLogServiceMethods.ByName("GetActivityLog")),
			connect.WithClientOptions(opts...),
		),
		getStressLog: connect.NewClient[recordlog.LogRequest, recordlog.StressLog](
			httpClient,
			baseURL+RecordLogServiceGetStressLogProcedure,
			connect.WithSchema(recordLogServiceMethods.ByName("GetStressLog")),
			connect.WithClientOptions(opts...),
		),
		getStoolLog: connect.NewClient[recordlog.LogRequest, recordlog.StoolLog](
			httpClient,
			baseURL+RecordLogServiceGetStoolLogProcedure,
			connect.WithSchema(recordLogServiceMethods.ByName("GetStoolLog")),
			connect.WithClientOptions(opts...),
		),
	}
}

// recordLogServiceClient implements RecordLogServiceClient.
type recordLogServiceClient struct {
	getBodyMetricsLog     *connect.Client[recordlog.LogRequest, recordlog.BodyMetricsLog]
	getSleepLog           *connect.Client[recordlog.LogRequest, recordlog.SleepLog]
	getMealLog            *connect.Client[recordlog.LogRequest, recordlog.MealLog]
	getAlcoholCaffeineLog *connect.Client[recordlog.LogRequest, recordlog.AlcoholCaffeineLog]
	getTabaccoLog         *connect.Client[recordlog.LogRequest, recordlog.TabaccoLog]
	getActivityLog        *connect.Client[recordlog.LogRequest, recordlog.ActivityLog]
	getStressLog          *connect.Client[recordlog.LogRequest, recordlog.StressLog]
	getStoolLog           *connect.Client[recordlog.LogRequest, recordlog.StoolLog]
}

// GetBodyMetricsLog calls taomics.praman.recordlog.RecordLogService.GetBodyMetricsLog.
func (c *recordLogServiceClient) GetBodyMetricsLog(ctx context.Context, req *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.BodyMetricsLog], error) {
	return c.getBodyMetricsLog.CallUnary(ctx, req)
}

// GetSleepLog calls taomics.praman.recordlog.RecordLogService.GetSleepLog.
func (c *recordLogServiceClient) GetSleepLog(ctx context.Context, req *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.SleepLog], error) {
	return c.getSleepLog.CallUnary(ctx, req)
}

// GetMealLog calls taomics.praman.recordlog.RecordLogService.GetMealLog.
func (c *recordLogServiceClient) GetMealLog(ctx context.Context, req *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.MealLog], error) {
	return c.getMealLog.CallUnary(ctx, req)
}

// GetAlcoholCaffeineLog calls taomics.praman.recordlog.RecordLogService.GetAlcoholCaffeineLog.
func (c *recordLogServiceClient) GetAlcoholCaffeineLog(ctx context.Context, req *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.AlcoholCaffeineLog], error) {
	return c.getAlcoholCaffeineLog.CallUnary(ctx, req)
}

// GetTabaccoLog calls taomics.praman.recordlog.RecordLogService.GetTabaccoLog.
func (c *recordLogServiceClient) GetTabaccoLog(ctx context.Context, req *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.TabaccoLog], error) {
	return c.getTabaccoLog.CallUnary(ctx, req)
}

// GetActivityLog calls taomics.praman.recordlog.RecordLogService.GetActivityLog.
func (c *recordLogServiceClient) GetActivityLog(ctx context.Context, req *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.ActivityLog], error) {
	return c.getActivityLog.CallUnary(ctx, req)
}

// GetStressLog calls taomics.praman.recordlog.RecordLogService.GetStressLog.
func (c *recordLogServiceClient) GetStressLog(ctx context.Context, req *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.StressLog], error) {
	return c.getStressLog.CallUnary(ctx, req)
}

// GetStoolLog calls taomics.praman.recordlog.RecordLogService.GetStoolLog.
func (c *recordLogServiceClient) GetStoolLog(ctx context.Context, req *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.StoolLog], error) {
	return c.getStoolLog.CallUnary(ctx, req)
}

// RecordLogServiceHandler is an implementation of the taomics.praman.recordlog.RecordLogService
// service.
type RecordLogServiceHandler interface {
	// Gets the current user's log of body metrics.
	GetBodyMetricsLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.BodyMetricsLog], error)
	// Gets the current user's log of sleep journal.
	GetSleepLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.SleepLog], error)
	// Gets the current user's log of meal journal.
	GetMealLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.MealLog], error)
	// Gets the current user's log of alcohol and caffeine journal.
	GetAlcoholCaffeineLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.AlcoholCaffeineLog], error)
	// Gets the current user's log of tabacco journal.
	GetTabaccoLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.TabaccoLog], error)
	// Gets the current user's log of activity journal.
	GetActivityLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.ActivityLog], error)
	// Gets the current user's log of stress journal.
	GetStressLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.StressLog], error)
	// Gets the current user's log of stool journal.
	GetStoolLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.StoolLog], error)
}

// NewRecordLogServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRecordLogServiceHandler(svc RecordLogServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	recordLogServiceMethods := recordlog.File_recordlog_recordlog_proto.Services().ByName("RecordLogService").Methods()
	recordLogServiceGetBodyMetricsLogHandler := connect.NewUnaryHandler(
		RecordLogServiceGetBodyMetricsLogProcedure,
		svc.GetBodyMetricsLog,
		connect.WithSchema(recordLogServiceMethods.ByName("GetBodyMetricsLog")),
		connect.WithHandlerOptions(opts...),
	)
	recordLogServiceGetSleepLogHandler := connect.NewUnaryHandler(
		RecordLogServiceGetSleepLogProcedure,
		svc.GetSleepLog,
		connect.WithSchema(recordLogServiceMethods.ByName("GetSleepLog")),
		connect.WithHandlerOptions(opts...),
	)
	recordLogServiceGetMealLogHandler := connect.NewUnaryHandler(
		RecordLogServiceGetMealLogProcedure,
		svc.GetMealLog,
		connect.WithSchema(recordLogServiceMethods.ByName("GetMealLog")),
		connect.WithHandlerOptions(opts...),
	)
	recordLogServiceGetAlcoholCaffeineLogHandler := connect.NewUnaryHandler(
		RecordLogServiceGetAlcoholCaffeineLogProcedure,
		svc.GetAlcoholCaffeineLog,
		connect.WithSchema(recordLogServiceMethods.ByName("GetAlcoholCaffeineLog")),
		connect.WithHandlerOptions(opts...),
	)
	recordLogServiceGetTabaccoLogHandler := connect.NewUnaryHandler(
		RecordLogServiceGetTabaccoLogProcedure,
		svc.GetTabaccoLog,
		connect.WithSchema(recordLogServiceMethods.ByName("GetTabaccoLog")),
		connect.WithHandlerOptions(opts...),
	)
	recordLogServiceGetActivityLogHandler := connect.NewUnaryHandler(
		RecordLogServiceGetActivityLogProcedure,
		svc.GetActivityLog,
		connect.WithSchema(recordLogServiceMethods.ByName("GetActivityLog")),
		connect.WithHandlerOptions(opts...),
	)
	recordLogServiceGetStressLogHandler := connect.NewUnaryHandler(
		RecordLogServiceGetStressLogProcedure,
		svc.GetStressLog,
		connect.WithSchema(recordLogServiceMethods.ByName("GetStressLog")),
		connect.WithHandlerOptions(opts...),
	)
	recordLogServiceGetStoolLogHandler := connect.NewUnaryHandler(
		RecordLogServiceGetStoolLogProcedure,
		svc.GetStoolLog,
		connect.WithSchema(recordLogServiceMethods.ByName("GetStoolLog")),
		connect.WithHandlerOptions(opts...),
	)
	return "/taomics.praman.recordlog.RecordLogService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RecordLogServiceGetBodyMetricsLogProcedure:
			recordLogServiceGetBodyMetricsLogHandler.ServeHTTP(w, r)
		case RecordLogServiceGetSleepLogProcedure:
			recordLogServiceGetSleepLogHandler.ServeHTTP(w, r)
		case RecordLogServiceGetMealLogProcedure:
			recordLogServiceGetMealLogHandler.ServeHTTP(w, r)
		case RecordLogServiceGetAlcoholCaffeineLogProcedure:
			recordLogServiceGetAlcoholCaffeineLogHandler.ServeHTTP(w, r)
		case RecordLogServiceGetTabaccoLogProcedure:
			recordLogServiceGetTabaccoLogHandler.ServeHTTP(w, r)
		case RecordLogServiceGetActivityLogProcedure:
			recordLogServiceGetActivityLogHandler.ServeHTTP(w, r)
		case RecordLogServiceGetStressLogProcedure:
			recordLogServiceGetStressLogHandler.ServeHTTP(w, r)
		case RecordLogServiceGetStoolLogProcedure:
			recordLogServiceGetStoolLogHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRecordLogServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRecordLogServiceHandler struct{}

func (UnimplementedRecordLogServiceHandler) GetBodyMetricsLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.BodyMetricsLog], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.recordlog.RecordLogService.GetBodyMetricsLog is not implemented"))
}

func (UnimplementedRecordLogServiceHandler) GetSleepLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.SleepLog], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.recordlog.RecordLogService.GetSleepLog is not implemented"))
}

func (UnimplementedRecordLogServiceHandler) GetMealLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.MealLog], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.recordlog.RecordLogService.GetMealLog is not implemented"))
}

func (UnimplementedRecordLogServiceHandler) GetAlcoholCaffeineLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.AlcoholCaffeineLog], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.recordlog.RecordLogService.GetAlcoholCaffeineLog is not implemented"))
}

func (UnimplementedRecordLogServiceHandler) GetTabaccoLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.TabaccoLog], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.recordlog.RecordLogService.GetTabaccoLog is not implemented"))
}

func (UnimplementedRecordLogServiceHandler) GetActivityLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.ActivityLog], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.recordlog.RecordLogService.GetActivityLog is not implemented"))
}

func (UnimplementedRecordLogServiceHandler) GetStressLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.StressLog], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.recordlog.RecordLogService.GetStressLog is not implemented"))
}

func (UnimplementedRecordLogServiceHandler) GetStoolLog(context.Context, *connect.Request[recordlog.LogRequest]) (*connect.Response[recordlog.StoolLog], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.recordlog.RecordLogService.GetStoolLog is not implemented"))
}
