// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: lifestylejournal/lifestylejournal.proto

package lifestylejournalconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	lifestylejournal "github.com/taomics/pramanapi/lifestylejournal"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LifestyleJournalServiceName is the fully-qualified name of the LifestyleJournalService service.
	LifestyleJournalServiceName = "taomics.praman.lifestylejournal.LifestyleJournalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LifestyleJournalServiceKeepJournalProcedure is the fully-qualified name of the
	// LifestyleJournalService's KeepJournal RPC.
	LifestyleJournalServiceKeepJournalProcedure = "/taomics.praman.lifestylejournal.LifestyleJournalService/KeepJournal"
	// LifestyleJournalServiceEvaluateChallengeScoresProcedure is the fully-qualified name of the
	// LifestyleJournalService's EvaluateChallengeScores RPC.
	LifestyleJournalServiceEvaluateChallengeScoresProcedure = "/taomics.praman.lifestylejournal.LifestyleJournalService/EvaluateChallengeScores"
)

// LifestyleJournalServiceClient is a client for the
// taomics.praman.lifestylejournal.LifestyleJournalService service.
type LifestyleJournalServiceClient interface {
	// Keep a journal.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	KeepJournal(context.Context, *connect.Request[lifestylejournal.LifestyleJournalKeepingRequest]) (*connect.Response[lifestylejournal.LifestyleJournalKeepingResponse], error)
	// Evaluate the challenge scores based on the latest journal records.
	// It requires a minimum number of journal records to perform an evaluation.
	//
	// Errors:
	//   - FAILED_PRECONDITION (9): Not enough journal records to evaluate the
	//     challenge scores.
	EvaluateChallengeScores(context.Context, *connect.Request[lifestylejournal.LifestyleJournalEvaluateChallengeScoresRequest]) (*connect.Response[lifestylejournal.LifestyleJournalEvaluateChallengeScoresResponse], error)
}

// NewLifestyleJournalServiceClient constructs a client for the
// taomics.praman.lifestylejournal.LifestyleJournalService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLifestyleJournalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LifestyleJournalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lifestyleJournalServiceMethods := lifestylejournal.File_lifestylejournal_lifestylejournal_proto.Services().ByName("LifestyleJournalService").Methods()
	return &lifestyleJournalServiceClient{
		keepJournal: connect.NewClient[lifestylejournal.LifestyleJournalKeepingRequest, lifestylejournal.LifestyleJournalKeepingResponse](
			httpClient,
			baseURL+LifestyleJournalServiceKeepJournalProcedure,
			connect.WithSchema(lifestyleJournalServiceMethods.ByName("KeepJournal")),
			connect.WithClientOptions(opts...),
		),
		evaluateChallengeScores: connect.NewClient[lifestylejournal.LifestyleJournalEvaluateChallengeScoresRequest, lifestylejournal.LifestyleJournalEvaluateChallengeScoresResponse](
			httpClient,
			baseURL+LifestyleJournalServiceEvaluateChallengeScoresProcedure,
			connect.WithSchema(lifestyleJournalServiceMethods.ByName("EvaluateChallengeScores")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lifestyleJournalServiceClient implements LifestyleJournalServiceClient.
type lifestyleJournalServiceClient struct {
	keepJournal             *connect.Client[lifestylejournal.LifestyleJournalKeepingRequest, lifestylejournal.LifestyleJournalKeepingResponse]
	evaluateChallengeScores *connect.Client[lifestylejournal.LifestyleJournalEvaluateChallengeScoresRequest, lifestylejournal.LifestyleJournalEvaluateChallengeScoresResponse]
}

// KeepJournal calls taomics.praman.lifestylejournal.LifestyleJournalService.KeepJournal.
func (c *lifestyleJournalServiceClient) KeepJournal(ctx context.Context, req *connect.Request[lifestylejournal.LifestyleJournalKeepingRequest]) (*connect.Response[lifestylejournal.LifestyleJournalKeepingResponse], error) {
	return c.keepJournal.CallUnary(ctx, req)
}

// EvaluateChallengeScores calls
// taomics.praman.lifestylejournal.LifestyleJournalService.EvaluateChallengeScores.
func (c *lifestyleJournalServiceClient) EvaluateChallengeScores(ctx context.Context, req *connect.Request[lifestylejournal.LifestyleJournalEvaluateChallengeScoresRequest]) (*connect.Response[lifestylejournal.LifestyleJournalEvaluateChallengeScoresResponse], error) {
	return c.evaluateChallengeScores.CallUnary(ctx, req)
}

// LifestyleJournalServiceHandler is an implementation of the
// taomics.praman.lifestylejournal.LifestyleJournalService service.
type LifestyleJournalServiceHandler interface {
	// Keep a journal.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	KeepJournal(context.Context, *connect.Request[lifestylejournal.LifestyleJournalKeepingRequest]) (*connect.Response[lifestylejournal.LifestyleJournalKeepingResponse], error)
	// Evaluate the challenge scores based on the latest journal records.
	// It requires a minimum number of journal records to perform an evaluation.
	//
	// Errors:
	//   - FAILED_PRECONDITION (9): Not enough journal records to evaluate the
	//     challenge scores.
	EvaluateChallengeScores(context.Context, *connect.Request[lifestylejournal.LifestyleJournalEvaluateChallengeScoresRequest]) (*connect.Response[lifestylejournal.LifestyleJournalEvaluateChallengeScoresResponse], error)
}

// NewLifestyleJournalServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLifestyleJournalServiceHandler(svc LifestyleJournalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lifestyleJournalServiceMethods := lifestylejournal.File_lifestylejournal_lifestylejournal_proto.Services().ByName("LifestyleJournalService").Methods()
	lifestyleJournalServiceKeepJournalHandler := connect.NewUnaryHandler(
		LifestyleJournalServiceKeepJournalProcedure,
		svc.KeepJournal,
		connect.WithSchema(lifestyleJournalServiceMethods.ByName("KeepJournal")),
		connect.WithHandlerOptions(opts...),
	)
	lifestyleJournalServiceEvaluateChallengeScoresHandler := connect.NewUnaryHandler(
		LifestyleJournalServiceEvaluateChallengeScoresProcedure,
		svc.EvaluateChallengeScores,
		connect.WithSchema(lifestyleJournalServiceMethods.ByName("EvaluateChallengeScores")),
		connect.WithHandlerOptions(opts...),
	)
	return "/taomics.praman.lifestylejournal.LifestyleJournalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LifestyleJournalServiceKeepJournalProcedure:
			lifestyleJournalServiceKeepJournalHandler.ServeHTTP(w, r)
		case LifestyleJournalServiceEvaluateChallengeScoresProcedure:
			lifestyleJournalServiceEvaluateChallengeScoresHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLifestyleJournalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLifestyleJournalServiceHandler struct{}

func (UnimplementedLifestyleJournalServiceHandler) KeepJournal(context.Context, *connect.Request[lifestylejournal.LifestyleJournalKeepingRequest]) (*connect.Response[lifestylejournal.LifestyleJournalKeepingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.lifestylejournal.LifestyleJournalService.KeepJournal is not implemented"))
}

func (UnimplementedLifestyleJournalServiceHandler) EvaluateChallengeScores(context.Context, *connect.Request[lifestylejournal.LifestyleJournalEvaluateChallengeScoresRequest]) (*connect.Response[lifestylejournal.LifestyleJournalEvaluateChallengeScoresResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.lifestylejournal.LifestyleJournalService.EvaluateChallengeScores is not implemented"))
}
