// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: externaldata/externaldata.proto

package externaldataconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	externaldata "github.com/taomics/pramanapi/externaldata"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ExternalDataServiceName is the fully-qualified name of the ExternalDataService service.
	ExternalDataServiceName = "taomics.praman.externaldata.ExternalDataService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ExternalDataServiceStoreExternalDataProcedure is the fully-qualified name of the
	// ExternalDataService's StoreExternalData RPC.
	ExternalDataServiceStoreExternalDataProcedure = "/taomics.praman.externaldata.ExternalDataService/StoreExternalData"
	// ExternalDataServiceDeleteExternalDataProcedure is the fully-qualified name of the
	// ExternalDataService's DeleteExternalData RPC.
	ExternalDataServiceDeleteExternalDataProcedure = "/taomics.praman.externaldata.ExternalDataService/DeleteExternalData"
	// ExternalDataServiceGetExternalDataSummaryProcedure is the fully-qualified name of the
	// ExternalDataService's GetExternalDataSummary RPC.
	ExternalDataServiceGetExternalDataSummaryProcedure = "/taomics.praman.externaldata.ExternalDataService/GetExternalDataSummary"
)

// ExternalDataServiceClient is a client for the taomics.praman.externaldata.ExternalDataService
// service.
type ExternalDataServiceClient interface {
	// Store external data.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	StoreExternalData(context.Context, *connect.Request[externaldata.StoreExternalDataRequest]) (*connect.Response[externaldata.StoreExternalDataResponse], error)
	// Delete external data for the current user.
	//
	// A successful response indicates that data in the specified source group
	// is no longer associated with the current user. Internal processing for
	// preserving other source groups or physical cleanup may continue or be
	// handled separately.
	//
	// Specify EXTERNAL_DATA_SOURCE_GROUP_ALL to delete all external data.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): Source group is unspecified or invalid.
	//   - RESOURCE_EXHAUSTED (8): Another deletion was completed within the last hour.
	DeleteExternalData(context.Context, *connect.Request[externaldata.DeleteExternalDataRequest]) (*connect.Response[externaldata.DeleteExternalDataResponse], error)
	// Get external data summary.
	// Errors:
	//   - NOT_FOUND (5): Specified source is not found.
	GetExternalDataSummary(context.Context, *connect.Request[externaldata.ExternalDataSummaryRequest]) (*connect.Response[externaldata.ExternalDataSummaryResponse], error)
}

// NewExternalDataServiceClient constructs a client for the
// taomics.praman.externaldata.ExternalDataService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExternalDataServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExternalDataServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	externalDataServiceMethods := externaldata.File_externaldata_externaldata_proto.Services().ByName("ExternalDataService").Methods()
	return &externalDataServiceClient{
		storeExternalData: connect.NewClient[externaldata.StoreExternalDataRequest, externaldata.StoreExternalDataResponse](
			httpClient,
			baseURL+ExternalDataServiceStoreExternalDataProcedure,
			connect.WithSchema(externalDataServiceMethods.ByName("StoreExternalData")),
			connect.WithClientOptions(opts...),
		),
		deleteExternalData: connect.NewClient[externaldata.DeleteExternalDataRequest, externaldata.DeleteExternalDataResponse](
			httpClient,
			baseURL+ExternalDataServiceDeleteExternalDataProcedure,
			connect.WithSchema(externalDataServiceMethods.ByName("DeleteExternalData")),
			connect.WithClientOptions(opts...),
		),
		getExternalDataSummary: connect.NewClient[externaldata.ExternalDataSummaryRequest, externaldata.ExternalDataSummaryResponse](
			httpClient,
			baseURL+ExternalDataServiceGetExternalDataSummaryProcedure,
			connect.WithSchema(externalDataServiceMethods.ByName("GetExternalDataSummary")),
			connect.WithClientOptions(opts...),
		),
	}
}

// externalDataServiceClient implements ExternalDataServiceClient.
type externalDataServiceClient struct {
	storeExternalData      *connect.Client[externaldata.StoreExternalDataRequest, externaldata.StoreExternalDataResponse]
	deleteExternalData     *connect.Client[externaldata.DeleteExternalDataRequest, externaldata.DeleteExternalDataResponse]
	getExternalDataSummary *connect.Client[externaldata.ExternalDataSummaryRequest, externaldata.ExternalDataSummaryResponse]
}

// StoreExternalData calls taomics.praman.externaldata.ExternalDataService.StoreExternalData.
func (c *externalDataServiceClient) StoreExternalData(ctx context.Context, req *connect.Request[externaldata.StoreExternalDataRequest]) (*connect.Response[externaldata.StoreExternalDataResponse], error) {
	return c.storeExternalData.CallUnary(ctx, req)
}

// DeleteExternalData calls taomics.praman.externaldata.ExternalDataService.DeleteExternalData.
func (c *externalDataServiceClient) DeleteExternalData(ctx context.Context, req *connect.Request[externaldata.DeleteExternalDataRequest]) (*connect.Response[externaldata.DeleteExternalDataResponse], error) {
	return c.deleteExternalData.CallUnary(ctx, req)
}

// GetExternalDataSummary calls
// taomics.praman.externaldata.ExternalDataService.GetExternalDataSummary.
func (c *externalDataServiceClient) GetExternalDataSummary(ctx context.Context, req *connect.Request[externaldata.ExternalDataSummaryRequest]) (*connect.Response[externaldata.ExternalDataSummaryResponse], error) {
	return c.getExternalDataSummary.CallUnary(ctx, req)
}

// ExternalDataServiceHandler is an implementation of the
// taomics.praman.externaldata.ExternalDataService service.
type ExternalDataServiceHandler interface {
	// Store external data.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): There is an invalid argument
	StoreExternalData(context.Context, *connect.Request[externaldata.StoreExternalDataRequest]) (*connect.Response[externaldata.StoreExternalDataResponse], error)
	// Delete external data for the current user.
	//
	// A successful response indicates that data in the specified source group
	// is no longer associated with the current user. Internal processing for
	// preserving other source groups or physical cleanup may continue or be
	// handled separately.
	//
	// Specify EXTERNAL_DATA_SOURCE_GROUP_ALL to delete all external data.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): Source group is unspecified or invalid.
	//   - RESOURCE_EXHAUSTED (8): Another deletion was completed within the last hour.
	DeleteExternalData(context.Context, *connect.Request[externaldata.DeleteExternalDataRequest]) (*connect.Response[externaldata.DeleteExternalDataResponse], error)
	// Get external data summary.
	// Errors:
	//   - NOT_FOUND (5): Specified source is not found.
	GetExternalDataSummary(context.Context, *connect.Request[externaldata.ExternalDataSummaryRequest]) (*connect.Response[externaldata.ExternalDataSummaryResponse], error)
}

// NewExternalDataServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExternalDataServiceHandler(svc ExternalDataServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	externalDataServiceMethods := externaldata.File_externaldata_externaldata_proto.Services().ByName("ExternalDataService").Methods()
	externalDataServiceStoreExternalDataHandler := connect.NewUnaryHandler(
		ExternalDataServiceStoreExternalDataProcedure,
		svc.StoreExternalData,
		connect.WithSchema(externalDataServiceMethods.ByName("StoreExternalData")),
		connect.WithHandlerOptions(opts...),
	)
	externalDataServiceDeleteExternalDataHandler := connect.NewUnaryHandler(
		ExternalDataServiceDeleteExternalDataProcedure,
		svc.DeleteExternalData,
		connect.WithSchema(externalDataServiceMethods.ByName("DeleteExternalData")),
		connect.WithHandlerOptions(opts...),
	)
	externalDataServiceGetExternalDataSummaryHandler := connect.NewUnaryHandler(
		ExternalDataServiceGetExternalDataSummaryProcedure,
		svc.GetExternalDataSummary,
		connect.WithSchema(externalDataServiceMethods.ByName("GetExternalDataSummary")),
		connect.WithHandlerOptions(opts...),
	)
	return "/taomics.praman.externaldata.ExternalDataService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExternalDataServiceStoreExternalDataProcedure:
			externalDataServiceStoreExternalDataHandler.ServeHTTP(w, r)
		case ExternalDataServiceDeleteExternalDataProcedure:
			externalDataServiceDeleteExternalDataHandler.ServeHTTP(w, r)
		case ExternalDataServiceGetExternalDataSummaryProcedure:
			externalDataServiceGetExternalDataSummaryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExternalDataServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExternalDataServiceHandler struct{}

func (UnimplementedExternalDataServiceHandler) StoreExternalData(context.Context, *connect.Request[externaldata.StoreExternalDataRequest]) (*connect.Response[externaldata.StoreExternalDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.externaldata.ExternalDataService.StoreExternalData is not implemented"))
}

func (UnimplementedExternalDataServiceHandler) DeleteExternalData(context.Context, *connect.Request[externaldata.DeleteExternalDataRequest]) (*connect.Response[externaldata.DeleteExternalDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.externaldata.ExternalDataService.DeleteExternalData is not implemented"))
}

func (UnimplementedExternalDataServiceHandler) GetExternalDataSummary(context.Context, *connect.Request[externaldata.ExternalDataSummaryRequest]) (*connect.Response[externaldata.ExternalDataSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("taomics.praman.externaldata.ExternalDataService.GetExternalDataSummary is not implemented"))
}
