// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: researchstudy/researchstudy.proto

package researchstudy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResearchStudyService_ListResearchStudies_FullMethodName = "/taomics.praman.researchstudy.ResearchStudyService/ListResearchStudies"
	ResearchStudyService_GetResearchStudy_FullMethodName    = "/taomics.praman.researchstudy.ResearchStudyService/GetResearchStudy"
)

// ResearchStudyServiceClient is the client API for ResearchStudyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # ResearchStudyService
//
// This service presents research information and the current user's relation
// to research studies. It does not manage study enrollment, informed consent,
// data-provision workflow, or ethics-review workflows.
//
// Research-study definitions are application-managed static data. The service
// uses persistent storage only for dynamic relations such as the association
// between a user and a study.
//
// Common Errors:
//   - INTERNAL (13): An unexpected server error occurred.
//   - UNAUTHENTICATED (16): Authentication failed.
type ResearchStudyServiceClient interface {
	// List research studies visible to the current user.
	//
	// The response contains:
	//   - all public studies; and
	//   - non-public studies for which the current user is registered as a
	//     target.
	ListResearchStudies(ctx context.Context, in *ListResearchStudiesRequest, opts ...grpc.CallOption) (*ListResearchStudiesResponse, error)
	// Get detailed information about a research study.
	//
	// Detailed information is available only when the current user is registered
	// as a target of the specified study, including when the study is public.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): research_study_id is empty or invalid.
	//   - NOT_FOUND (5): The study does not exist or is not accessible to the
	//     current user.
	GetResearchStudy(ctx context.Context, in *GetResearchStudyRequest, opts ...grpc.CallOption) (*GetResearchStudyResponse, error)
}

type researchStudyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResearchStudyServiceClient(cc grpc.ClientConnInterface) ResearchStudyServiceClient {
	return &researchStudyServiceClient{cc}
}

func (c *researchStudyServiceClient) ListResearchStudies(ctx context.Context, in *ListResearchStudiesRequest, opts ...grpc.CallOption) (*ListResearchStudiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResearchStudiesResponse)
	err := c.cc.Invoke(ctx, ResearchStudyService_ListResearchStudies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *researchStudyServiceClient) GetResearchStudy(ctx context.Context, in *GetResearchStudyRequest, opts ...grpc.CallOption) (*GetResearchStudyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResearchStudyResponse)
	err := c.cc.Invoke(ctx, ResearchStudyService_GetResearchStudy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResearchStudyServiceServer is the server API for ResearchStudyService service.
// All implementations must embed UnimplementedResearchStudyServiceServer
// for forward compatibility.
//
// # ResearchStudyService
//
// This service presents research information and the current user's relation
// to research studies. It does not manage study enrollment, informed consent,
// data-provision workflow, or ethics-review workflows.
//
// Research-study definitions are application-managed static data. The service
// uses persistent storage only for dynamic relations such as the association
// between a user and a study.
//
// Common Errors:
//   - INTERNAL (13): An unexpected server error occurred.
//   - UNAUTHENTICATED (16): Authentication failed.
type ResearchStudyServiceServer interface {
	// List research studies visible to the current user.
	//
	// The response contains:
	//   - all public studies; and
	//   - non-public studies for which the current user is registered as a
	//     target.
	ListResearchStudies(context.Context, *ListResearchStudiesRequest) (*ListResearchStudiesResponse, error)
	// Get detailed information about a research study.
	//
	// Detailed information is available only when the current user is registered
	// as a target of the specified study, including when the study is public.
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): research_study_id is empty or invalid.
	//   - NOT_FOUND (5): The study does not exist or is not accessible to the
	//     current user.
	GetResearchStudy(context.Context, *GetResearchStudyRequest) (*GetResearchStudyResponse, error)
	mustEmbedUnimplementedResearchStudyServiceServer()
}

// UnimplementedResearchStudyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResearchStudyServiceServer struct{}

func (UnimplementedResearchStudyServiceServer) ListResearchStudies(context.Context, *ListResearchStudiesRequest) (*ListResearchStudiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResearchStudies not implemented")
}
func (UnimplementedResearchStudyServiceServer) GetResearchStudy(context.Context, *GetResearchStudyRequest) (*GetResearchStudyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResearchStudy not implemented")
}
func (UnimplementedResearchStudyServiceServer) mustEmbedUnimplementedResearchStudyServiceServer() {}
func (UnimplementedResearchStudyServiceServer) testEmbeddedByValue()                              {}

// UnsafeResearchStudyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResearchStudyServiceServer will
// result in compilation errors.
type UnsafeResearchStudyServiceServer interface {
	mustEmbedUnimplementedResearchStudyServiceServer()
}

func RegisterResearchStudyServiceServer(s grpc.ServiceRegistrar, srv ResearchStudyServiceServer) {
	// If the following call pancis, it indicates UnimplementedResearchStudyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResearchStudyService_ServiceDesc, srv)
}

func _ResearchStudyService_ListResearchStudies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResearchStudiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResearchStudyServiceServer).ListResearchStudies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResearchStudyService_ListResearchStudies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResearchStudyServiceServer).ListResearchStudies(ctx, req.(*ListResearchStudiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResearchStudyService_GetResearchStudy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResearchStudyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResearchStudyServiceServer).GetResearchStudy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResearchStudyService_GetResearchStudy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResearchStudyServiceServer).GetResearchStudy(ctx, req.(*GetResearchStudyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResearchStudyService_ServiceDesc is the grpc.ServiceDesc for ResearchStudyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResearchStudyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taomics.praman.researchstudy.ResearchStudyService",
	HandlerType: (*ResearchStudyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListResearchStudies",
			Handler:    _ResearchStudyService_ListResearchStudies_Handler,
		},
		{
			MethodName: "GetResearchStudy",
			Handler:    _ResearchStudyService_GetResearchStudy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "researchstudy/researchstudy.proto",
}
