// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: healthfeedback/healthfeedback.proto

package healthfeedback

import (
	context "context"
	pramanapi "github.com/taomics/pramanapi"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthFeedbackService_GetHealthFeedback_FullMethodName  = "/taomics.praman.healthfeedback.HealthFeedbackService/GetHealthFeedback"
	HealthFeedbackService_RateHealthFeedback_FullMethodName = "/taomics.praman.healthfeedback.HealthFeedbackService/RateHealthFeedback"
	HealthFeedbackService_SetHealthMode_FullMethodName      = "/taomics.praman.healthfeedback.HealthFeedbackService/SetHealthMode"
)

// HealthFeedbackServiceClient is the client API for HealthFeedbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # HealthFeedbackService
//
// Common Errors:
//   - INTERNAL (13): Server is something wrong.
//   - UNAUTHENTICATED (16): Authorization header is something wrong.
//   - PERMISSION_DENIED (7): User is not authorized.
type HealthFeedbackServiceClient interface {
	// GetHealthFeedback
	//
	// Errors:
	//   - NOT_FOUND (5): there is no feedback.
	//   - FAILED_PRECONDITION (9): health mode is not set.
	GetHealthFeedback(ctx context.Context, in *GetHealthFeedbackRequest, opts ...grpc.CallOption) (*GetHealthFeedbackResponse, error)
	// RateHealthFeedback
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): id is invalid, or rating is UNRATED.
	RateHealthFeedback(ctx context.Context, in *RateHealthFeedbackRequest, opts ...grpc.CallOption) (*pramanapi.Empty, error)
	// SetHealthMode
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): mode is missing.
	SetHealthMode(ctx context.Context, in *SetHealthModeRequest, opts ...grpc.CallOption) (*pramanapi.Empty, error)
}

type healthFeedbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthFeedbackServiceClient(cc grpc.ClientConnInterface) HealthFeedbackServiceClient {
	return &healthFeedbackServiceClient{cc}
}

func (c *healthFeedbackServiceClient) GetHealthFeedback(ctx context.Context, in *GetHealthFeedbackRequest, opts ...grpc.CallOption) (*GetHealthFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthFeedbackResponse)
	err := c.cc.Invoke(ctx, HealthFeedbackService_GetHealthFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthFeedbackServiceClient) RateHealthFeedback(ctx context.Context, in *RateHealthFeedbackRequest, opts ...grpc.CallOption) (*pramanapi.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pramanapi.Empty)
	err := c.cc.Invoke(ctx, HealthFeedbackService_RateHealthFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthFeedbackServiceClient) SetHealthMode(ctx context.Context, in *SetHealthModeRequest, opts ...grpc.CallOption) (*pramanapi.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pramanapi.Empty)
	err := c.cc.Invoke(ctx, HealthFeedbackService_SetHealthMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthFeedbackServiceServer is the server API for HealthFeedbackService service.
// All implementations must embed UnimplementedHealthFeedbackServiceServer
// for forward compatibility.
//
// # HealthFeedbackService
//
// Common Errors:
//   - INTERNAL (13): Server is something wrong.
//   - UNAUTHENTICATED (16): Authorization header is something wrong.
//   - PERMISSION_DENIED (7): User is not authorized.
type HealthFeedbackServiceServer interface {
	// GetHealthFeedback
	//
	// Errors:
	//   - NOT_FOUND (5): there is no feedback.
	//   - FAILED_PRECONDITION (9): health mode is not set.
	GetHealthFeedback(context.Context, *GetHealthFeedbackRequest) (*GetHealthFeedbackResponse, error)
	// RateHealthFeedback
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): id is invalid, or rating is UNRATED.
	RateHealthFeedback(context.Context, *RateHealthFeedbackRequest) (*pramanapi.Empty, error)
	// SetHealthMode
	//
	// Errors:
	//   - INVALID_ARGUMENT (3): mode is missing.
	SetHealthMode(context.Context, *SetHealthModeRequest) (*pramanapi.Empty, error)
	mustEmbedUnimplementedHealthFeedbackServiceServer()
}

// UnimplementedHealthFeedbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthFeedbackServiceServer struct{}

func (UnimplementedHealthFeedbackServiceServer) GetHealthFeedback(context.Context, *GetHealthFeedbackRequest) (*GetHealthFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealthFeedback not implemented")
}
func (UnimplementedHealthFeedbackServiceServer) RateHealthFeedback(context.Context, *RateHealthFeedbackRequest) (*pramanapi.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateHealthFeedback not implemented")
}
func (UnimplementedHealthFeedbackServiceServer) SetHealthMode(context.Context, *SetHealthModeRequest) (*pramanapi.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHealthMode not implemented")
}
func (UnimplementedHealthFeedbackServiceServer) mustEmbedUnimplementedHealthFeedbackServiceServer() {}
func (UnimplementedHealthFeedbackServiceServer) testEmbeddedByValue()                               {}

// UnsafeHealthFeedbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthFeedbackServiceServer will
// result in compilation errors.
type UnsafeHealthFeedbackServiceServer interface {
	mustEmbedUnimplementedHealthFeedbackServiceServer()
}

func RegisterHealthFeedbackServiceServer(s grpc.ServiceRegistrar, srv HealthFeedbackServiceServer) {
	// If the following call pancis, it indicates UnimplementedHealthFeedbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthFeedbackService_ServiceDesc, srv)
}

func _HealthFeedbackService_GetHealthFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthFeedbackServiceServer).GetHealthFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthFeedbackService_GetHealthFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthFeedbackServiceServer).GetHealthFeedback(ctx, req.(*GetHealthFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthFeedbackService_RateHealthFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateHealthFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthFeedbackServiceServer).RateHealthFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthFeedbackService_RateHealthFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthFeedbackServiceServer).RateHealthFeedback(ctx, req.(*RateHealthFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthFeedbackService_SetHealthMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHealthModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthFeedbackServiceServer).SetHealthMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthFeedbackService_SetHealthMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthFeedbackServiceServer).SetHealthMode(ctx, req.(*SetHealthModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthFeedbackService_ServiceDesc is the grpc.ServiceDesc for HealthFeedbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthFeedbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taomics.praman.healthfeedback.HealthFeedbackService",
	HandlerType: (*HealthFeedbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealthFeedback",
			Handler:    _HealthFeedbackService_GetHealthFeedback_Handler,
		},
		{
			MethodName: "RateHealthFeedback",
			Handler:    _HealthFeedbackService_RateHealthFeedback_Handler,
		},
		{
			MethodName: "SetHealthMode",
			Handler:    _HealthFeedbackService_SetHealthMode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "healthfeedback/healthfeedback.proto",
}
